const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Pins the reviewed profile-specific ABI list in generated `android/gradle.properties`.
 *
 * Why a plugin: this project is managed — `android/` is gitignored and regenerated by
 * `expo prebuild` on every (EAS) build — so editing `gradle.properties` by hand, or exporting
 * `ORG_GRADLE_PROJECT_reactNativeArchitectures` for one command, does not survive. The default
 * Expo template emits all four ABIs (`armeabi-v7a,arm64-v8a,x86,x86_64`), and each one is a full
 * native compile of React Native, Hermes, op-sqlite/SQLCipher, libsodium and the local modules.
 *
 * Dropping to one cuts the native build to roughly a quarter of its work and, more importantly on
 * this machine, a quarter of its peak memory: the release build has repeatedly been OOM-killed by
 * macOS when free RAM was short, and a killed build still burns a Play versionCode (eas.json uses
 * `appVersionSource: remote` + `autoIncrement`, so the counter moves when the build STARTS).
 *
 * Production keeps the deliberately narrow arm64-v8a artifact. Development and preview also build
 * x86_64 so Android Studio's supported 64-bit emulator can install them. The app config defaults a
 * plain local prebuild to that development list and EAS profiles pass one of the two exact reviewed
 * values below.
 */
const DEVELOPMENT_ARCHITECTURES = 'arm64-v8a,x86_64';
const APPROVED_ARCHITECTURES = new Set(['arm64-v8a', DEVELOPMENT_ARCHITECTURES]);

module.exports = function withArm64Only(
  config,
  { architectures = DEVELOPMENT_ARCHITECTURES } = {},
) {
  if (typeof architectures !== 'string' || !APPROVED_ARCHITECTURES.has(architectures)) {
    throw new Error(
      `Invalid Gator Android architectures: ${JSON.stringify(architectures)}. ` +
        `Expected "arm64-v8a" or "${DEVELOPMENT_ARCHITECTURES}".`,
    );
  }

  return withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === 'property' && item.key === 'reactNativeArchitectures',
    );
    if (existing) {
      existing.value = architectures;
    } else {
      cfg.modResults.push({
        type: 'property',
        key: 'reactNativeArchitectures',
        value: architectures,
      });
    }
    return cfg;
  });
};
