const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Builds Android for **arm64-v8a only** by pinning `reactNativeArchitectures` in the generated
 * `android/gradle.properties`.
 *
 * Why a plugin: this project is managed — `android/` is gitignored and regenerated by
 * `expo prebuild` on every (EAS) build — so editing `gradle.properties` by hand, or exporting
 * `ORG_GRADLE_PROJECT_reactNativeArchitectures` for one command, does not survive. The default
 * Expo template emits all four ABIs (`armeabi-v7a,arm64-v8a,x86,x86_64`), and each one is a full
 * native compile of React Native, Hermes, op-sqlite/SQLCipher, libsodium and the local modules.
 *
 * Dropping to one cuts the native build to roughly a quarter of its work and, more importantly on
 * this machine, a quarter of its peak memory: the release build has repeatedly been OOM-killed by
 * macOS when free RAM was short, and a killed build still burns a Play versionCode (eas.json uses
 * `appVersionSource: remote` + `autoIncrement`, so the counter moves when the build STARTS).
 *
 * WHAT THIS GIVES UP: 32-bit ARM devices (`armeabi-v7a`) and the x86/x86_64 emulator images can no
 * longer install the artifact. Play simply does not offer the release to them — it is a filter, not
 * a crash. Every 64-bit Android phone since ~2015 is arm64-v8a, and Play has required 64-bit
 * support since 2019, so the practical cost is old 32-bit hardware and Intel emulators. If you ever
 * need an emulator build, add the ABI back here rather than passing a one-off `-P` flag, so the
 * change is visible in review.
 */
const ARCHITECTURES = 'arm64-v8a';

module.exports = function withArm64Only(config) {
  return withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === 'property' && item.key === 'reactNativeArchitectures',
    );
    if (existing) {
      existing.value = ARCHITECTURES;
    } else {
      cfg.modResults.push({
        type: 'property',
        key: 'reactNativeArchitectures',
        value: ARCHITECTURES,
      });
    }
    return cfg;
  });
};
