const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Injects a dedicated Android notification status-bar icon (`ic_stat_gator`) into the
 * native res/ folders at prebuild time.
 *
 * Why a plugin: this project is managed — `android/` is gitignored and regenerated by
 * `expo prebuild` on every (EAS) build — so hand-placed drawables don't survive. This
 * copies the pre-sized density PNGs from `assets/notification/` into the generated
 * `res/drawable-<density>/` folders so `smallIcon: 'ic_stat_gator'` resolves.
 *
 * The PNGs are white-on-transparent silhouettes (Android tints notification small icons),
 * one per density bucket, sized to the 24dp status-bar convention.
 */
const DENSITIES = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'];
const RES_NAME = 'ic_stat_gator.png';

module.exports = function withNotificationIcon(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const { projectRoot, platformProjectRoot } = cfg.modRequest;
      const resRoot = path.join(platformProjectRoot, 'app', 'src', 'main', 'res');
      for (const density of DENSITIES) {
        const src = path.join(projectRoot, 'assets', 'notification', `ic_stat_gator-${density}.png`);
        if (!fs.existsSync(src)) {
          throw new Error(`withNotificationIcon: missing source icon ${src}`);
        }
        const destDir = path.join(resRoot, `drawable-${density}`);
        fs.mkdirSync(destDir, { recursive: true });
        fs.copyFileSync(src, path.join(destDir, RES_NAME));
      }
      return cfg;
    },
  ]);
};
