const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Declares an Android Direct Share target ("Sharing Shortcuts") so Gator can surface in the
 * PRIORITIZED row of the system share sheet — the "share straight to a person/conversation" band
 * above the generic app list — instead of only the lower all-apps list.
 *
 * Why a plugin: this project is managed — `android/` is gitignored and regenerated by `expo
 * prebuild` on every (EAS) build — so a hand-edited manifest / res file wouldn't survive. This
 * writes `res/xml/shortcuts.xml` with a <share-target> and points MainActivity at it via the
 * `android.app.shortcuts` meta-data.
 *
 * IMPORTANT — this is the DECLARATION half only. Android shows Direct Share results for a
 * <share-target> only once the app ALSO publishes matching dynamic shortcuts at runtime, tagged
 * with the SAME category. That half lives in the local native module `modules/gator-share-shortcuts`
 * (driven from `src/services/shortcuts/shareShortcuts.ts`); both category strings must stay
 * identical or Android surfaces nothing. The generic app-list entry (from the SEND intent filters
 * in app.config.ts) is independent and keeps working regardless.
 */

// Kept in sync with app.config.ts `android.package`.
const PACKAGE = 'com.bluegreengatorapps.messages';
const MAIN_ACTIVITY = `${PACKAGE}.MainActivity`;
const SHARE_TARGET_CATEGORY = `${PACKAGE}.category.SHARE_TARGET`;

// `*/*` on purpose. Android only offers Direct Share targets for a mime type the <share-target>
// DECLARES, so listing only image/video/text meant a shared PDF (or audio, zip, vCard…) matched no
// share-target and the priority row came back EMPTY — even though the app's SEND intent filters
// accept `*/*` and the shortcuts were published correctly. It must stay a subset of those filters
// (see the expo-share-intent block in app.config.ts, which declares `*/*`).
const SHORTCUTS_XML = `<?xml version="1.0" encoding="utf-8"?>
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <share-target android:targetClass="${MAIN_ACTIVITY}">
    <data android:mimeType="*/*" />
    <category android:name="${SHARE_TARGET_CATEGORY}" />
  </share-target>
</shortcuts>
`;

/** Write res/xml/shortcuts.xml into the generated native project. */
function withShortcutsResource(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'shortcuts.xml'), SHORTCUTS_XML);
      return cfg;
    },
  ]);
}

/** Point MainActivity (the LAUNCHER activity) at the shortcuts resource. */
function withShortcutsMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(cfg.modResults);
    activity['meta-data'] = activity['meta-data'] ?? [];
    const already = activity['meta-data'].some(
      (m) => m.$?.['android:name'] === 'android.app.shortcuts',
    );
    if (!already) {
      activity['meta-data'].push({
        $: { 'android:name': 'android.app.shortcuts', 'android:resource': '@xml/shortcuts' },
      });
    }
    return cfg;
  });
}

module.exports = function withShareTargets(config) {
  return withShortcutsMetaData(withShortcutsResource(config));
};
