const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Declares an Android Direct Share target ("Sharing Shortcuts") so Gator can surface in the
 * PRIORITIZED row of the system share sheet — the "share straight to a person/conversation" band
 * above the generic app list — instead of only the lower all-apps list.
 *
 * Why a plugin: this project is managed — `android/` is gitignored and regenerated by `expo
 * prebuild` on every (EAS) build — so a hand-edited manifest / res file wouldn't survive. This
 * writes `res/xml/shortcuts.xml` with a <share-target> and points MainActivity at it via the
 * `android.app.shortcuts` meta-data.
 *
 * IMPORTANT — this is the DECLARATION only. Android only shows Direct Share results for a
 * <share-target> once the app also PUBLISHES matching dynamic shortcuts at runtime
 * (ShortcutManagerCompat.pushDynamicShortcut, tagged with SHARE_TARGET_CATEGORY, one per recent
 * chat). That runtime step is a native follow-up; until it lands this declaration is the required
 * foundation but won't by itself populate the priority row. The generic app-list entry (from the
 * SEND intent filters) is unaffected and keeps working.
 */

// Kept in sync with app.config.ts `android.package`.
const PACKAGE = 'com.bluegreengatorapps.messages';
const MAIN_ACTIVITY = `${PACKAGE}.MainActivity`;
const SHARE_TARGET_CATEGORY = `${PACKAGE}.category.SHARE_TARGET`;

const SHORTCUTS_XML = `<?xml version="1.0" encoding="utf-8"?>
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <share-target android:targetClass="${MAIN_ACTIVITY}">
    <data android:mimeType="image/*" />
    <data android:mimeType="video/*" />
    <data android:mimeType="text/*" />
    <category android:name="${SHARE_TARGET_CATEGORY}" />
  </share-target>
</shortcuts>
`;

/** Write res/xml/shortcuts.xml into the generated native project. */
function withShortcutsResource(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'shortcuts.xml'), SHORTCUTS_XML);
      return cfg;
    },
  ]);
}

/** Point MainActivity (the LAUNCHER activity) at the shortcuts resource. */
function withShortcutsMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(cfg.modResults);
    activity['meta-data'] = activity['meta-data'] ?? [];
    const already = activity['meta-data'].some(
      (m) => m.$?.['android:name'] === 'android.app.shortcuts',
    );
    if (!already) {
      activity['meta-data'].push({
        $: { 'android:name': 'android.app.shortcuts', 'android:resource': '@xml/shortcuts' },
      });
    }
    return cfg;
  });
}

module.exports = function withShareTargets(config) {
  return withShortcutsMetaData(withShortcutsResource(config));
};
